version: '3.8'

services:
  db:
    image: postgres:14
    container_name: email-assistant-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EMAIL_SERVICE_USERNAME=${EMAIL_SERVICE_USERNAME}
      - EMAIL_SERVICE_PASSWORD=${EMAIL_SERVICE_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
    ports:
      - "5001:5001"
    depends_on:
      db:
        condition: service_healthy

  dashboard:
    build:
      context: .
      dockerfile: docker/dashboard/Dockerfile
    environment:
      - API_URL=http://api:5001
    ports:
      - "8501:8501"
    depends_on:
      - api

volumes:
  postgres_data:
    driver: local