version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - FLASK_DEBUG=1
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EMAIL_SERVICE_USERNAME=${EMAIL_SERVICE_USERNAME}
      - EMAIL_SERVICE_PASSWORD=${EMAIL_SERVICE_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
    ports:
      - "5001:5001"
    depends_on:
      db:
        condition: service_healthy
    command: ["flask", "run", "--host=0.0.0.0", "--port=5001", "--debug"]

  dashboard:
    build:
      context: .
      dockerfile: docker/dashboard/Dockerfile
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - API_URL=http://api:5001
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - api
    command: ["streamlit", "run", "src/dashboard/email_monitor.py", "--server.port=8501", "--server.address=0.0.0.0"]

volumes:
  postgres_data: 