"""Add thread_id and recipient_email to ConversationMessage

Revision ID: 3434c26163c0
Revises: 1a2b3c4d5e6f
Create Date: 2025-01-29 00:21:51.688833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3434c26163c0'
down_revision: Union[str, None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_messages', sa.Column('recipient_email', sa.String(length=255), nullable=True))
    op.add_column('conversation_messages', sa.Column('thread_id', sa.String(length=255), nullable=True))
    op.add_column('conversation_messages', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('conversation_messages', 'direction',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('INCOMING', 'OUTGOING', name='messagedirection'),
               existing_nullable=False)
    op.create_index(op.f('ix_conversation_messages_recipient_email'), 'conversation_messages', ['recipient_email'], unique=False)
    op.create_index(op.f('ix_conversation_messages_thread_id'), 'conversation_messages', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_messages_thread_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_recipient_email'), table_name='conversation_messages')
    op.alter_column('conversation_messages', 'direction',
               existing_type=sa.Enum('INCOMING', 'OUTGOING', name='messagedirection'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('conversation_messages', 'updated_at')
    op.drop_column('conversation_messages', 'thread_id')
    op.drop_column('conversation_messages', 'recipient_email')
    # ### end Alembic commands ###
