export interface EmailConfig {
  imap: {
    host: string;
    port: string;
    username: string;
    password: string;
    secure: boolean;
  };
  smtp: {
    host: string;
    port: string;
    username: string;
    password: string;
    secure: boolean;
  };
  autoResponse: {
    enabled: boolean;
    adminEmail: string;
    summaryEnabled: boolean;
    responseDelay: string;
    workingHours: {
      start: string;
      end: string;
    };
    excludedEmails: string;
    customSignature: string;
  };
}

export interface ProcessedEmail {
  id: string;
  from: string;
  to: string[];
  subject: string;
  content: string;
  timestamp: string;
  attachments?: Array<{
    filename: string;
    content: Buffer;
    contentType: string;
  }>;
  status?: 'new' | 'processing' | 'analyzed' | 'responded' | 'error';
  analysis?: EmailAnalysis;
  error?: string;
}

export interface EmailAnalysis {
  summary: string;
  key_points: string[];
  sentiment: string;
  priority: string;
  action_items: string[];
  category: string;
  requiresMeeting: boolean;
  suggestedTimeRange?: {
    start: Date;
    end: Date;
  };
  meetingContext?: string;
  additionalAttendees?: string[];
  confidence: number;
  tags: string[];
}

export interface EmailResponse {
  subject: string;
  body: string;
  to: string[];
  cc?: string[];
  attachments?: Array<{
    filename: string;
    content: Buffer;
    contentType: string;
  }>;
  metadata?: {
    priority: string;
    category: string;
    responseType: string;
    autoGenerated: boolean;
  };
}

export interface EmailMetrics {
  totalProcessed: number;
  successfulResponses: number;
  failedResponses: number;
  averageResponseTime: number;
  responseRate: number;
  categories: Record<string, number>;
  priorities: Record<string, number>;
  hourlyDistribution: Record<string, number>;
} 